pipeline {
  agent {
    docker { image 'node:latest' }
  }
  stages {
    stage('Install') {
      steps{
        dir('./colorpad-app/'){ sh 'npm install' }
      }
    }

    stage('Test') {
      parallel {
        stage('Unit tests') {
          steps{
            dir('./colorpad-app/') { sh 'ng test' }
          }
        }
        stage('End to End tests') {
          steps{
            dir('./colorpad-app/') { sh 'ng e2e' }
          }
        }
      }
    }

    stage('Build') {
      steps{
        dir('./colorpad-app/') { sh 'npm run-script build' }
      }
    }
  }
}
