pipeline {
  agent {
    docker { image 'node:latest' }
  }
  stages {
    stage('Install') {
      steps{
        dir('./colorpad-app/'){ sh 'npm install' }
      }
    }

    stage('Build') {
      steps{
        dir('./colorpad-app/') { sh 'npm run-script build' }
      }
    }
  }
}
