pipeline {
  agent {
    docker { image 'node:latest' }
  }
  stages {
    stage('Install') {
      steps { sh 'npm install' }
    }

    stage('Test') {
      parallel {
        stage('Static code analysis') {
            steps { sh 'npm run-script tslint.json' }
        }
        stage('Unit tests') {
            steps { sh 'ng test' }
        }
        stage('End to End tests') {
            steps { sh 'ng e2e' }
        }
      }
    }

    stage('Build') {
      steps { sh 'npm run-script build' }
    }
  }
}
